### PR TITLE
Edit menu endpoint

### PR DESCRIPTION
**Pull request by PeanutPancakes**
Edit menu endpoint
This feature adds an api endpoint at /edit-menu which allows users to create and update menus. Issue #23 

MessManagementTests

##  Checklist
- [✔] I have tested in local Environment.
- [✔] I have made the fix as per issue conversation

### CODE REVIEW

**Comment by adityabisht02** [comment]
We can use unix time while logging user attendance( this will be a different api) for now just use the day to pinpoint the menu that needs to be changed.

**Comment by adityabisht02** [comment]
@Jothebanner any updates?

**Comment by PeanutPancakes** [comment]
@adityabisht02 I changed the day to be between 1 and 7. Let me know if there is anything else that needs to change. Thanks!

**Comment by PeanutPancakes** [comment]
Hey @adityabisht02, I updated the endpoint to work with primer data.

**Comment by adityabisht02** [comment]
Looks good, sorry I couldnt respond earlier

**Pull request merged**
