### PR TITLE
add login functionality

### PR DESCRIPTION
**Pull request by leksyking**

### CODE REVIEW

**Review by adityabisht02 — COMMENTED** [review]
Add the json parser middleware , u can look at admin/users.js to see how to implement that. Without the json parser you cant read from req.body.

**Comment by leksyking** [comment]
Of course

**Comment by leksyking** [comment]
The thing is the middleware should be in the index.js file so we don't have to write it in every file again.
Also express middleware has the functionalities provided by body-parser as it is based on body-parser.

**Comment by leksyking** [comment]
```
{
    "error": false,
    "results": [
        {
            "id": 2,
            "name": "Leksyking",
            "email": "gggmailcom",
            "phone": 65748
        }
    ],
    "msg": "You have successfully logged in"
}
```
Login result

**Comment by adityabisht02** [comment]
Is the mysql2 package better than mysql in any way?

**Comment by adityabisht02** [comment]
And I had a question, the app object is using the express.json() middleware but we are not using the app object for apis , we are using the router so wouldn't that be a problem?

**Comment by leksyking** [comment]
I was told to use when I encountered a problem while debugging. But I forgot to change it back
I didn't notice any difference by the way.

**Comment by leksyking** [comment]
No using the app object in the  indexjs only can not pose any problem
Express has simplified everything
You don't need to add the router as the app middleware

**Comment by leksyking** [comment]
The router works well like that

**Pull request merged**
