### PR TITLE
[Feat]: Created the Admin Login API

### LINKED ISSUE #44: Create admin sign in
If the admin username and password are present in the table ,send a positive response. 
U can take the username and password from request body. Use only the username and password to log in , other fields
like email and id are not required here.

### PR DESCRIPTION
**Pull request by harpreet0102**
## PR Title

The purpose of this Pull Request is to fix #44 >

##  Checklist
- [ ] I have tested in local Environment.
- [ ] I have made the fix as per issue converstaion

### CODE REVIEW

**Comment by adityabisht02** [comment]
Please attach a postman screenshot

**Comment by harpreet0102** [comment]
Sure!

**Comment by harpreet0102** [comment]
Screenshot from 2022-10-27 15-16-40 
 This is the postman screenshot

**Comment by harpreet0102** [comment]
Screenshot from 2022-10-27 15-19-23
This the sample admin table. The entries are filled using the signup API.

**Comment by harpreet0102** [comment]
Screenshot from 2022-10-27 15-22-12
You can refer this as well

**Pull request merged**
