### PR TITLE
added edit-user-details api on admin level

### PR DESCRIPTION
**Pull request by Harsh-garg-coder**
1. added edit-user-details api.
2. changed the datatype of phone from int to varchar as its going out of range.

### CODE REVIEW

**Review by adityabisht02 — COMMENTED** [review]
Looks good would appreciate if u can attach a postman screenshot as well here

**Comment by Harsh-garg-coder** [comment]
Ok i will attach that in the evening

**Comment by Harsh-garg-coder** [comment]
Screenshot 2022-10-15 at 10 54 26 PM

**Comment by adityabisht02** [comment]
Looks good!

**Pull request merged**
