### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by OjasMittal**
Created License

### CODE REVIEW

**Comment by adityabisht02** [comment]
Whats the difference between the 3 licences

**Comment by adityabisht02** [comment]
the templates I mean

**Comment by OjasMittal** [comment]
Those three are almost the same,no major differences just that GNU version 3 is the latest with updated policies and hence is regarded as the best.

**Review by alicalimli — COMMENTED** [review]
Nice!

**Comment by adityabisht02** [comment]
@alicalimli yo nice to see you here

**Comment by adityabisht02** [comment]
@OjasMittal alright great then

**Pull request merged**
